import type { AudioEvidence, TitleIdentity } from '../services/englishAudio.js';

export interface NetflixDub extends TitleIdentity, AudioEvidence {
  name: string;
  category: 'korean-drama' | 'anime';
  identity_source: string;
}

// Previously verified audio evidence. This snapshot annotates titles, never supplies genre results.
// Evidence of an English track on the public US listing, not every region/episode.
export const NETFLIX_DUBS: readonly NetflixDub[] = [
  {
    "media_type": "movie",
    "tmdb_id": 1295026,
    "name": "100 METERS",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q134007355",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81785821",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 667520,
    "name": "A Whisker Away",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q85881910",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81281872",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 643058,
    "name": "Aggretsuko: We Wish You a Metal Christmas",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q60159757",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81008536",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 297438,
    "name": "Akane-banashi",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q135641513",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82701514",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 665251,
    "name": "Altered Carbon: Resleeved",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q90302055",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81001991",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 717022,
    "name": "Anpanman: Nanda and Runda from Star of Toys",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q24876572",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81719826",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 591077,
    "name": "Anpanman: Shine! Kulun and the Stars of Life",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q48758921",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81719828",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 361609,
    "name": "Anpanman: Star-Spirited Dollie",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q11270545",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81719799",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 615676,
    "name": "Anpanman: Twinkle! Princess Vanilla of Ice Cream Land",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q60989824",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81719829",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 62110,
    "name": "Assassination Classroom",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q50376961",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80045948",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 1263421,
    "name": "Baki Hanma VS Kengan Ashura",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q126393619",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81648184",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 156898,
    "name": "BASTARD‼ -Heavy Metal, Dark Fantasy-",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q112184946",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81281582",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 90937,
    "name": "BEASTARS",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q62583787",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81054847",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 207347,
    "name": "Blue Box",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q123484832",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81663323",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 839100,
    "name": "Bright: Samurai Soul",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q108582044",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81001990",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 912598,
    "name": "Bubble",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q109965531",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81345945",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 77240,
    "name": "Captain Tsubasa",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q56322464",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81003894",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 312949,
    "name": "Chainsmoker Cat",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q137971300",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82760630",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 628964,
    "name": "Child of Kamiari Month",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q106645541",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81478031",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 1575337,
    "name": "Cosmic Princess Kaguya!",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q136708889",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81756595",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 105248,
    "name": "Cyberpunk: Edgerunners",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q96677963",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81054853",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 207784,
    "name": "Delicious in Dungeon",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q118692115",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81564899",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 85937,
    "name": "Demon Slayer: Kimetsu no Yaiba",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q63350570",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81091393",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 30983,
    "name": "Detective Conan",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q5363072",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80090370",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 75208,
    "name": "Devilman Crybaby",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q47087518",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80174974",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 96884,
    "name": "Dragon Quest: The Adventure of Dai",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q107047182",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81374392",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 92591,
    "name": "Drifting Dragons",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q95472074",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80992788",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 877957,
    "name": "Drifting Home",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q109602795",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81328781",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 857862,
    "name": "EVANGELION: DEATH (TRUE)²",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q65045161",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81033473",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 68854,
    "name": "From Me to You: Kimi ni Todoke",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q116982481",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80236253",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 111177,
    "name": "Godzilla Singular Point",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q100977481",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80234811",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 449574,
    "name": "Godzilla: Planet of the Monsters",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q26456695",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80180373",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 536115,
    "name": "Godzilla: The Planet Eater",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q56275759",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80198623",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 12477,
    "name": "Grave of the Fireflies",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q274520",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/557010",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 93816,
    "name": "Great Pretender",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q83712396",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81220435",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 21729,
    "name": "Gurren Lagann",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q4277",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70213196",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 615165,
    "name": "Her Blue Sky",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q65277404",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81427482",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 46298,
    "name": "Hunter x Hunter",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q70209136",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70300472",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 239523,
    "name": "Hunter x Hunter: The Last Mission",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q15205223",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80108453",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 35610,
    "name": "InuYasha",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q21587460",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70204995",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 810693,
    "name": "Jujutsu Kaisen 0",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q109914608",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81602834",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 62741,
    "name": "Kamisama Kiss",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q115639779",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80070071",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 90660,
    "name": "KENGAN ASHURA",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q66363944",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80992228",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 123876,
    "name": "Komi Can't Communicate",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q107985188",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81228573",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 306762,
    "name": "Love Through a Prism",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q137043454",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81498882",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 845387,
    "name": "maboroshi",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q118552001",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81450803",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 34158,
    "name": "Magic Knight Rayearth",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q127717083",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70308293",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 204832,
    "name": "MASHLE: MAGIC AND MUSCLES",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q115754239",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81685164",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 67075,
    "name": "Mob Psycho 100",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q66313196",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80179798",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 685274,
    "name": "Mobile Suit Gundam Hathaway",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q109289213",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81439253",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 989730,
    "name": "Mononoke the Movie: The Phantom in the Rain",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q128153071",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81580574",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 1230393,
    "name": "Monsters 103 Mercies Dragon Damnation",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q124040202",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81733654",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 123249,
    "name": "My Dress-Up Darling",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q109426380",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81569754",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 65930,
    "name": "My Hero Academia",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q63686324",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80135674",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 1231574,
    "name": "My Oni Girl",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q124879766",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81582442",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 20982,
    "name": "Naruto Shippuden the Movie",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q75690",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70124999",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 75624,
    "name": "Naruto Shippuden the Movie: Blood Prison",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q718536",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80152537",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 17581,
    "name": "Naruto Shippuden the Movie: Bonds",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q703524",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70105699",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 50723,
    "name": "Naruto Shippuden the Movie: The Lost Tower",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q75682",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70275937",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 36728,
    "name": "Naruto Shippuden the Movie: The Will of Fire",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q703571",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80045673",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 18861,
    "name": "Naruto the Movie: Guardians of the Crescent Moon Kingdom",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q696646",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70108386",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 16910,
    "name": "Naruto the Movie: Legend of the Stone of Gelel",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q696366",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70101321",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 16907,
    "name": "Naruto the Movie: Ninja Clash in the Land of Snow",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q696351",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70074559",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 890,
    "name": "Neon Genesis Evangelion",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q662",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81033445",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 594188,
    "name": "NiNoKuni",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q65007238",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81093113",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 37854,
    "name": "One Piece",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q710324",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80107103",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 1043,
    "name": "Ouran High School Host Club",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q109421585",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70205014",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 91997,
    "name": "PLUTO",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q116783101",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81281344",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 259140,
    "name": "Ranma1/2",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q126904533",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81171925",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 133121,
    "name": "Resident Evil: Damnation",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q150044",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70229183",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 400136,
    "name": "Resident Evil: Vendetta",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q22681637",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80190911",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 241138,
    "name": "Rising Impact",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q128795805",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81563026",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 210879,
    "name": "Rurouni Kenshin",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q114220519",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81705252",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 207332,
    "name": "SAKAMOTO DAYS",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q126127689",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81663325",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 10926,
    "name": "Sonic X",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q428130",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81172267",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 265712,
    "name": "Stand by Me Doraemon",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q15293047",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80158156",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 728754,
    "name": "Stand by Me Doraemon 2",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q78185552",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81451264",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 127599,
    "name": "Super Crooks",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q107093027",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81034907",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 916224,
    "name": "Suzume",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q110126272",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81696498",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 236385,
    "name": "T・P BON",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q125100989",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81497635",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 220542,
    "name": "The Apothecary Diaries",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q116787865",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81712068",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 67676,
    "name": "The Disastrous Life of Saiki K.",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q55229501",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80117781",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 783675,
    "name": "The First Slam Dunk",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q112897629",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81765372",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 271607,
    "name": "The Fragrant Flower Blooms with Dignity",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q130305455",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82024665",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 913001,
    "name": "The Imaginary",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q110166508",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81565710",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 84669,
    "name": "The Quintessential Quintuplets",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q62593542",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81152346",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 1679730,
    "name": "THE RIBBON HERO",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q139545724",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81493703",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 1021679,
    "name": "The Rose of Versailles",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q126958217",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81177638",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 843241,
    "name": "The Seven Deadly Sins: Cursed by Light",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q107377427",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81263946",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 278196,
    "name": "The Summer Hikaru Died",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q126080512",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81948057",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 39659,
    "name": "TIGER & BUNNY",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q114681531",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80039972",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 17149,
    "name": "Vampire Knight",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q115945467",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/70309457",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 610892,
    "name": "Violet Evergarden: Eternity and the Auto Memory Doll",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q73896191",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81208936",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 533514,
    "name": "Violet Evergarden: The Movie",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q106434135",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81193214",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 223500,
    "name": "WIND BREAKER",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q117336999",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81771389",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "movie",
    "tmdb_id": 579741,
    "name": "Words Bubble Up Like Soda Pop",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q85871409",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81400497",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 112166,
    "name": "Yasuke",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q106404099",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80990863",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 61663,
    "name": "Your Lie in April",
    "category": "anime",
    "identity_source": "https://www.wikidata.org/entity/Q91333870",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80041089",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 202783,
    "name": "A Killer Paradox",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q115413158",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81607354",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 296206,
    "name": "Agent Kim Reactivated",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q139553270",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82682338",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 135157,
    "name": "Alchemy of Souls",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q110890248",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81517188",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 99966,
    "name": "All of Us Are Dead",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q96414952",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81237994",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 271885,
    "name": "As You Stood By",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q132130038",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81900129",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 127529,
    "name": "Bloodhounds",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q109767798",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81444051",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 280945,
    "name": "Bon Appétit, Your Majesty",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q131910461",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82024852",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 281016,
    "name": "Boyfriend on Demand",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q132561179",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82007623",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 229891,
    "name": "Can This Love Be Translated?",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q125121395",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81697769",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 94796,
    "name": "Crash Landing on You",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q65258113",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81159258",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 110534,
    "name": "D.P.",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q105226735",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81280917",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 205319,
    "name": "Daily Dose of Sunshine",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q116033324",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81572595",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 215001,
    "name": "Destined with You",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q116550095",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81669779",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 281013,
    "name": "Dynamite Kiss",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q136373942",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82037587",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 197067,
    "name": "Extraordinary Attorney Woo",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q110118400",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81518991",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 152511,
    "name": "Forecasting Love and Weather",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q107343177",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81572781",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 305644,
    "name": "Four Hands, Two Sonatas",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q137271520",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82682404",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 228689,
    "name": "Genie, Make a Wish",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q126414646",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81748484",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 135238,
    "name": "Gyeongseong Creature",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q110614173",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81618079",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 106651,
    "name": "Hellbound",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q100934044",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81256675",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 226527,
    "name": "Hierarchy",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q124480568",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81624364",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 96102,
    "name": "Hospital Playlist",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q83625648",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81239224",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 285838,
    "name": "If Wishes Could Kill",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q137836018",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81975196",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 112833,
    "name": "Juvenile Justice",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q108688881",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81312802",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 233686,
    "name": "Karma",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q131522846",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81703410",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 198004,
    "name": "King the Land",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q114243955",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81671440",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 70593,
    "name": "Kingdom",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q30947892",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/80180171",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 232766,
    "name": "Mercy for None",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q123305848",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81702777",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 290193,
    "name": "Mousetrap",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q140198906",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81991749",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 230448,
    "name": "Mr. Plankton",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q124795628",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81506124",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 218539,
    "name": "My Demon",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q120721044",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81716080",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 110356,
    "name": "My Name",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q105619096",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81011211",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 303143,
    "name": "My Royal Nemesis",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q136763742",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82682323",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 286360,
    "name": "Notes from the Last Row",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q137836165",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82032597",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 291496,
    "name": "Our Sticky Love",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q137835829",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82048302",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 215720,
    "name": "Queen of Tears",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q116921048",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81707950",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 235355,
    "name": "Resident Playbook",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q122854712",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81739042",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 287011,
    "name": "Sold Out on You",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q137711304",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82175564",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 298610,
    "name": "Spooky in Love",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q138266416",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82682401",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 93405,
    "name": "Squid Game",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q106582931",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81040344",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 276161,
    "name": "Teach You a Lesson",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q137844128",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81947300",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 300727,
    "name": "The Apartment Job",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q139455537",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82755552",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 273977,
    "name": "The Art of Sarah",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q131844525",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81904993",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 279323,
    "name": "The East Palace",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q137723110",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81778702",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 219652,
    "name": "The Frog",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q120240271",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81654427",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 136283,
    "name": "The Glory",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q113197148",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81519223",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 209110,
    "name": "The Price of Confession",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q131822507",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81757813",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 217553,
    "name": "The Trauma Code: Heroes on Call",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q124128670",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81677629",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 259837,
    "name": "The WONDERfools",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q130748503",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81948067",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 238084,
    "name": "Trigger",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q130597380",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81696655",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 129888,
    "name": "Twenty Five Twenty One",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q108809568",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81517168",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 117376,
    "name": "Vincenzo",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q101252455",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81365087",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 289424,
    "name": "We Are All Trying Here",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q137843064",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/82189639",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 200709,
    "name": "Weak Hero",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q116007300",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81742615",
    "audio_provider": "Netflix",
    "audio_region": "US"
  },
  {
    "media_type": "tv",
    "tmdb_id": 219246,
    "name": "When Life Gives You Tangerines",
    "category": "korean-drama",
    "identity_source": "https://www.wikidata.org/entity/Q117353211",
    "english": true,
    "checked_at": "2026-09-10",
    "audio_source": "https://www.netflix.com/us/title/81681535",
    "audio_provider": "Netflix",
    "audio_region": "US"
  }
];
